

from manim import *
from colour import Color

class Strategy(Scene):
    def construct(self):
        squares = VGroup(
            *[VGroup(Square(color=WHITE),
                     fill_opacity=0.5).scale(0.45) for j in range(64)]
        ).arrange_in_grid(8, 8, buff=0)
        self.play(Create(squares))
        self.wait(1)

        red_circ = Circle(color=Color(hue=0, saturation=1, luminance=0.5), fill_opacity=1).scale(0.35)
        red_circ_copy = red_circ.copy()
        red_circ.move_to(squares[14])
        red_circ_copy.move_to(squares[41])
        blue_circ = Circle(color=Color(hue=0.6, saturation=1, luminance=0.5), fill_opacity=1).scale(0.35)
        blue_circ.move_to(squares[31])
        blue_circ_copy = blue_circ.copy()
        blue_circ_copy.move_to(squares[63])
        green_circ = Circle(color=Color(hue=0.3, saturation=1, luminance=0.5), fill_opacity=1).scale(0.35)
        green_circ.move_to(squares[33])
        green_circ_copy = green_circ.copy()
        green_circ_copy.move_to(squares[51])
        yellow_circ = Circle(color=Color(hue=0.15, saturation=1, luminance=0.5), fill_opacity=1).scale(0.35)
        yellow_circ.move_to(squares[34])
        yellow_circ_copy = yellow_circ.copy()
        yellow_circ_copy.move_to(squares[44])
        orange_circ = Circle(color=Color(hue=0.1, saturation=1, luminance=0.5), fill_opacity=1).scale(0.35)
        orange_circ.move_to(squares[0])
        orange_circ_copy = orange_circ.copy()
        orange_circ_copy.move_to(squares[48])
        cyan_circ = Circle(color=Color(hue=0.5, saturation=1, luminance=0.5), fill_opacity=1).scale(0.35)
        cyan_circ.move_to(squares[35])
        cyan_circ_copy = cyan_circ.copy()
        cyan_circ_copy.move_to(squares[49])
        self.play(Write(red_circ), Write(red_circ_copy), Write(blue_circ), Write(blue_circ_copy), Write(green_circ), Write(green_circ_copy), Write(yellow_circ), Write(yellow_circ_copy), Write(orange_circ), Write(orange_circ_copy), Write(cyan_circ), Write(cyan_circ_copy))
        self.wait(4)
        self.bring_to_front(squares[56])
        self.play(squares[56].animate.set_color(YELLOW))
        self.wait(1)

        path = VMobject()
        dot = Dot()
        dot.set_color(Color(hue=0.3, saturation=1, luminance=0.5))
        dot.move_to(green_circ_copy.get_center())
        path.set_points_as_corners([dot.get_center(), dot.get_center()])
        path.set_color(Color(hue=0.3, saturation=1, luminance=0.5))
        path.stroke_width = 20
        def update_path(path):
            previous_path = path.copy()
            previous_path.add_points_as_corners([dot.get_center()])
            path.become(previous_path)
        path.add_updater(update_path)
        self.add(path, dot)
        self.play(dot.animate.move_to(squares[59].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[58].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[57].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[56].get_center()), run_time=0.5)
        self.wait(2)
        self.play(FadeOut(path), FadeOut(dot))
        dot.set_color(Color(hue=0, saturation=1, luminance=0.5))
        dot.move_to(red_circ_copy.get_center())
        path.set_points_as_corners([dot.get_center(), dot.get_center()])
        path.set_color(Color(hue=0, saturation=1, luminance=0.5))
        path.stroke_width = 20
        path.add_updater(update_path)
        self.add(path, dot)
        self.play(dot.animate.move_to(squares[42].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[50].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[58].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[57].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[56].get_center()), run_time=0.5)
        self.wait(2)

        self.play(FadeOut(path), FadeOut(dot))
        dot.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        dot.move_to(orange_circ_copy.get_center())
        path.set_points_as_corners([dot.get_center(), dot.get_center()])
        path.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        path.stroke_width = 20
        path.add_updater(update_path)
        self.add(path, dot)
        self.play(dot.animate.move_to(squares[56].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[57].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[58].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[59].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[60].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[61].get_center()), run_time=0.5)
        self.play(dot.animate.move_to(squares[62].get_center()), run_time=0.5)
        self.wait(2)
        self.play(FadeOut(path), FadeOut(dot), squares[56].animate.set_color(WHITE))
        self.wait(1)
        orange_line = Line(start=orange_circ_copy.get_center(), end=orange_circ.get_center())
        orange_line.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        orange_line.set_stroke(width=20)
        self.play(Create(orange_line))
        img_x = ImageMobject("images/x.png").scale(0.1)
        img_x.next_to(squares, LEFT)
        self.wait(1)
        self.play(FadeIn(img_x))
        self.wait(2)
        self.play(FadeOut(img_x), FadeOut(orange_line))
        o_line_1 = Line(start=squares[48].get_center(), end=squares[56].get_center())
        o_line_1.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        o_line_1.set_stroke(width=20)
        o_line_2 = Line(start=squares[56].get_center(), end=squares[62].get_center())
        o_line_2.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        o_line_2.set_stroke(width=20)
        o_line_3 = Line(start=squares[62].get_center(), end=squares[22].get_center())
        o_line_3.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        o_line_3.set_stroke(width=20)
        o_line_4 = Line(start=squares[22].get_center(), end=squares[23].get_center())
        o_line_4.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        o_line_4.set_stroke(width=20)
        o_line_5 = Line(start=squares[23].get_center(), end=squares[7].get_center())
        o_line_5.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        o_line_5.set_stroke(width=20)
        o_line_6 = Line(start=squares[7].get_center(), end=squares[0].get_center())
        o_line_6.set_color(Color(hue=0.1, saturation=1, luminance=0.5))
        o_line_6.set_stroke(width=20)
        self.play(Create(o_line_1), run_time=0.3)
        self.play(Create(o_line_2), run_time=0.3)
        self.play(Create(o_line_3), run_time=0.3)
        self.play(Create(o_line_4), run_time=0.3)
        self.play(Create(o_line_5), run_time=0.3)
        self.play(Create(o_line_6), run_time=0.3)
        self.wait(2)
        img_check = ImageMobject("images/check.png").scale(0.1)
        img_check.next_to(squares, LEFT)
        self.play(FadeIn(img_check))
        self.wait(2)
        self.play(FadeOut(img_check), FadeOut(o_line_1), FadeOut(o_line_2), FadeOut(o_line_3), FadeOut(o_line_4), FadeOut(o_line_5), FadeOut(o_line_6),
                  FadeOut(red_circ), FadeOut(red_circ_copy), FadeOut(blue_circ), FadeOut(blue_circ_copy), FadeOut(green_circ), FadeOut(green_circ_copy), FadeOut(yellow_circ), FadeOut(yellow_circ_copy), FadeOut(orange_circ), FadeOut(orange_circ_copy), FadeOut(cyan_circ), FadeOut(cyan_circ_copy),
                  FadeOut(squares))


